# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        image_cartes:
            uri_prefix: /images/cartes
            upload_destination: '%kernel.project_dir%/public/images/cartes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer